## DAY ONE ASSIGNMENT

In [4]:
#import the numpy library
import numpy as np

In [5]:
#generate a 5x5 matrix of random integers

a=np.random.randint(10,50, (5,5))
a

array([[44, 22, 14, 23, 49],
       [24, 13, 27, 17, 29],
       [43, 38, 44, 24, 26],
       [29, 44, 34, 38, 36],
       [30, 49, 49, 33, 35]])

In [8]:
#Slicing
#To call the elements FROM the THIRD row and the last THREE columns

a[2:,2:]

array([[44, 24, 26],
       [34, 38, 36],
       [49, 33, 35]])

In [9]:
#To call the elements FROM the THIRD row and the last TWO columns

a[2:, 3:]

array([[24, 26],
       [38, 36],
       [33, 35]])

In [10]:
#To call the elements FROM the THIRD row and the THIRD AND FOURTH columns

a[2:, 2:4]

array([[44, 24],
       [34, 38],
       [49, 33]])